package vista;

import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JProgressBar;

/**
 *
 */
public class DialogoCargando extends javax.swing.JDialog {

    private String tituloTarea;

    public String getTituloTarea() {
        return tituloTarea;
    }

    public void setTituloTarea(String tituloTarea) {
        this.tituloTarea = tituloTarea;
        lblTituloTarea.setText(tituloTarea);
    }

    private String estadoTarea;
    private String cantidad;

    public String getEstadoTarea() {
        return estadoTarea;
    }

    public void setEstadoTarea(String estadoTarea) {
        this.estadoTarea = estadoTarea;
        lblEstadoTarea.setText(estadoTarea);
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
        //jLabel2.setText(cantidad);
    }

    public JProgressBar getBarraProgresoTarea() {
        return barraProgresoTarea;
    }

    /** Constructor ...*/
    public DialogoCargando(Window ventana, String tituloTarea) {
        super(ventana);
        initComponents();
        setTituloTarea(tituloTarea);
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new utilidades.beans.Contenedor();
        contenedor1 = new utilidades.beans.Contenedor();
        contenedor2 = new utilidades.beans.Contenedor();
        lblTituloTarea = new utilidades.beans.Etiqueta();
        contenedor6 = new utilidades.beans.Contenedor();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barraProgresoTarea = new javax.swing.JProgressBar();
        contenedor3 = new utilidades.beans.Contenedor();
        lblEstadoTarea = new utilidades.beans.Etiqueta();
        contenedor4 = new utilidades.beans.Contenedor();
        contenedor5 = new utilidades.beans.Contenedor();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setUndecorated(true);

        contenedorPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        contenedorPrincipal.setLayout(new java.awt.BorderLayout());

        contenedor1.setBackground(new java.awt.Color(0, 170, 0));
        contenedor1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/banner_cargando_azul.png"))); // NOI18N
        contenedor1.setOpaque(false);
        contenedor1.setPreferredSize(new java.awt.Dimension(50, 50));
        contenedor1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        contenedor2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/tsp_icon_azul.png"))); // NOI18N
        contenedor2.setOpaque(false);
        contenedor2.setPreferredSize(new java.awt.Dimension(34, 40));
        contenedor2.setTipoEscaladoImagen(utilidades.ConstantesUtiles.EPP);

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        contenedor1.add(contenedor2);

        lblTituloTarea.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblTituloTarea.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTarea.setPreferredSize(new java.awt.Dimension(300, 40));
        lblTituloTarea.setText("[Título tarea]");
        contenedor1.add(lblTituloTarea);

        contenedorPrincipal.add(contenedor1, java.awt.BorderLayout.NORTH);

        contenedor6.setBackground(new java.awt.Color(255, 255, 255));
        contenedor6.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Espere, por favor...");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 55));
        contenedor6.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        barraProgresoTarea.setBackground(new java.awt.Color(255, 255, 255));
        barraProgresoTarea.setForeground(new java.awt.Color(255, 153, 85));
        barraProgresoTarea.setBorderPainted(false);
        barraProgresoTarea.setIndeterminate(true);
        barraProgresoTarea.setPreferredSize(new java.awt.Dimension(210, 18));
        barraProgresoTarea.setStringPainted(true);
        jPanel2.add(barraProgresoTarea);

        contenedor6.add(jPanel2, java.awt.BorderLayout.CENTER);

        contenedorPrincipal.add(contenedor6, java.awt.BorderLayout.CENTER);

        contenedor3.setBackground(new java.awt.Color(32, 172, 32));
        contenedor3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/banner_cargando_azul1.png"))); // NOI18N
        contenedor3.setOpaque(false);
        contenedor3.setPreferredSize(new java.awt.Dimension(100, 60));

        lblEstadoTarea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoTarea.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblEstadoTarea.setPreferredSize(new java.awt.Dimension(250, 60));
        lblEstadoTarea.setText("[Mensaje de estado de la tarea]");
        contenedor3.add(lblEstadoTarea);

        contenedorPrincipal.add(contenedor3, java.awt.BorderLayout.SOUTH);

        contenedor4.setDegradadoLineal(
            new utilidades.degradadolineal.DegradadoLineal(
                new utilidades.degradadolineal.Parada(new java.awt.Point(142, 71), new java.awt.Color(255, 255, 255, 255)),
                new utilidades.degradadolineal.Parada(new java.awt.Point(0, 71), new java.awt.Color(255, 255, 255, 255)),
                new utilidades.degradadolineal.Redondeo(0, 0),
                new utilidades.degradadolineal.BordeLineal(new java.awt.Color(212, 208, 200, 255), 0),
                new java.awt.Dimension(150, 150)
            )
        );
        contenedor4.setOpaque(false);
        contenedor4.setPreferredSize(new java.awt.Dimension(70, 100));

        javax.swing.GroupLayout contenedor4Layout = new javax.swing.GroupLayout(contenedor4);
        contenedor4.setLayout(contenedor4Layout);
        contenedor4Layout.setHorizontalGroup(
            contenedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        contenedor4Layout.setVerticalGroup(
            contenedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        contenedorPrincipal.add(contenedor4, java.awt.BorderLayout.EAST);

        contenedor5.setDegradadoLineal(
            new utilidades.degradadolineal.DegradadoLineal(
                new utilidades.degradadolineal.Parada(new java.awt.Point(0, 71), new java.awt.Color(255, 255, 255, 255)),
                new utilidades.degradadolineal.Parada(new java.awt.Point(142, 71), new java.awt.Color(255, 255, 255, 255)),
                new utilidades.degradadolineal.Redondeo(0, 0),
                new utilidades.degradadolineal.BordeLineal(new java.awt.Color(212, 208, 200, 255), 0),
                new java.awt.Dimension(150, 150)
            )
        );
        contenedor5.setOpaque(false);
        contenedor5.setPreferredSize(new java.awt.Dimension(70, 100));

        javax.swing.GroupLayout contenedor5Layout = new javax.swing.GroupLayout(contenedor5);
        contenedor5.setLayout(contenedor5Layout);
        contenedor5Layout.setHorizontalGroup(
            contenedor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        contenedor5Layout.setVerticalGroup(
            contenedor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        contenedorPrincipal.add(contenedor5, java.awt.BorderLayout.WEST);

        getContentPane().add(contenedorPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Dimension getSize() {
        return new Dimension(400, 200);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresoTarea;
    private utilidades.beans.Contenedor contenedor1;
    private utilidades.beans.Contenedor contenedor2;
    private utilidades.beans.Contenedor contenedor3;
    private utilidades.beans.Contenedor contenedor4;
    private utilidades.beans.Contenedor contenedor5;
    private utilidades.beans.Contenedor contenedor6;
    private utilidades.beans.Contenedor contenedorPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private utilidades.beans.Etiqueta lblEstadoTarea;
    private utilidades.beans.Etiqueta lblTituloTarea;
    // End of variables declaration//GEN-END:variables

}
